import type { PermissionRow, RecordAccess } from "./types";

const ALL_RECORD_ACCESS: RecordAccess[] = ["All Records", "Own Records"];

const LINKED_RECORD_ACCESS: RecordAccess[] = [
  "All Records",
  "All Trips linked with Service Appointments",
  "All Time Sheets linked with Service Appointments",
];

export const MOCK_PERMISSIONS: PermissionRow[] = [
  {
    id: "contacts",
    name: "Contacts",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "companies",
    name: "Companies",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "requests",
    name: "Requests",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "estimates",
    name: "Estimates",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "work-orders",
    name: "Work Orders",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "service-appointments",
    name: "Service Appointments",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "trips",
    name: "Trips",
    enabled: true,
    recordAccess: "All Trips linked with Service Appointments",
    availableAccessOptions: LINKED_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete"],
    availablePermissions: ["View", "Create", "Edit", "Delete"],
  },
  {
    id: "time-sheets",
    name: "Time Sheets",
    enabled: true,
    recordAccess: "All Time Sheets linked with Service Appointments",
    availableAccessOptions: LINKED_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Status"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Status"],
  },
  {
    id: "job-sheets",
    name: "Job Sheets",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Edit", "Download", "Print"],
    availablePermissions: ["View", "Edit", "Download", "Print"],
  },
  {
    id: "services-and-parts",
    name: "Services And Parts",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "assets",
    name: "Assets",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Change Owner"],
  },
  {
    id: "notes",
    name: "Notes",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit"],
    availablePermissions: ["View", "Create", "Edit"],
  },
  {
    id: "attachments",
    name: "Attachments",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete"],
    availablePermissions: ["View", "Create", "Edit", "Delete"],
  },
  {
    id: "invoices",
    name: "Invoices",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Download", "Print"],
    availablePermissions: ["View", "Create", "Download", "Print"],
  },
  {
    id: "payments",
    name: "Payments",
    enabled: true,
    recordAccess: "All Records",
    availableAccessOptions: ALL_RECORD_ACCESS,
    permissions: ["View", "Create", "Edit", "Delete", "Print"],
    availablePermissions: ["View", "Create", "Edit", "Delete", "Print"],
  },
];
